import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";
import { db } from "@repo/database";
import { env } from "../../config/env.config";
import type { PRReviewStateType, AgentComment } from "../review.state";
import { cleanupRepo } from "../context/clone-repo";

const createInstallationOctokit = (githubInstallationId: string) =>
    new Octokit({
        authStrategy: createAppAuth,
        auth: {
            appId: env.GITHUB_APP_ID,
            privateKey: env.GITHUB_PRIVATE_KEY.replace(/\\n/g, "\n"),
            installationId: Number(githubInstallationId),
        },
    });

type Section = { emoji: string; label: string; caution: string };

const CATEGORY_SECTION: Record<AgentComment["category"], Section> = {
    BUG:           { emoji: "🔍", label: "Potential Issues Found",   caution: "critical bugs" },
    SECURITY:      { emoji: "🔒", label: "Security Issues",          caution: "security vulnerabilities" },
    PERFORMANCE:   { emoji: "⚡", label: "Performance Optimization", caution: "performance issues" },
    REFACTOR:      { emoji: "💡", label: "Code Suggestions",         caution: "code quality improvements" },
    STYLE:         { emoji: "💡", label: "Code Suggestions",         caution: "code quality improvements" },
    DOCUMENTATION: { emoji: "📝", label: "Documentation",            caution: "documentation gaps" },
    TEST:          { emoji: "🧪", label: "Test Coverage",            caution: "test coverage gaps" },
    OTHER:         { emoji: "💡", label: "Other",                    caution: "other issues" },
};

const SECTION_ORDER: AgentComment["category"][] = [
    "BUG", "SECURITY", "PERFORMANCE", "REFACTOR", "STYLE", "DOCUMENTATION", "TEST", "OTHER",
];

const buildComment = (state: PRReviewStateType, comments: AgentComment[], durationMs: number): string => {
    const blockingCount = comments.filter((c) => c.blocking).length;
    const hasCriticalOrHigh = comments.some((c) => c.severity === "CRITICAL" || c.severity === "HIGH");
    const durationSec = (durationMs / 1000).toFixed(1);

    const verdict = hasCriticalOrHigh
        ? "⛔ **Changes requested** — blocking issues must be resolved before merging."
        : comments.length > 0
            ? "⚠️ **Review complete** — issues noted for your attention."
            : "✅ **Looks good!** — No issues found.";

    const lines: string[] = ["## Code Review", "", verdict, ""];

    if (blockingCount > 0) {
        lines.push(`> [!CAUTION]`);
        lines.push(`> ${blockingCount} blocking issue${blockingCount > 1 ? "s" : ""} must be fixed before this PR can merge.`);
        lines.push("");
    }

    // Group by category, deduplicate merged labels (REFACTOR+STYLE both → "Code Suggestions")
    const rendered = new Set<string>();
    for (const cat of SECTION_ORDER) {
        const catComments = comments.filter((c) => c.category === cat);
        if (catComments.length === 0) continue;

        const { emoji, label, caution } = CATEGORY_SECTION[cat];
        if (rendered.has(label)) {
            // already rendered this section label (e.g. STYLE after REFACTOR) — append to existing
            // just add items without re-printing header
        } else {
            rendered.add(label);
            lines.push(`### ${emoji} ${label}`);
            lines.push(`> [!CAUTION]`);
            lines.push(`> Found ${catComments.length} ${caution} to review.`);
            lines.push("");
            lines.push("**Issues:**");
            lines.push("");
        }

        for (const c of catComments) {
            const fileName = c.filePath.split("/").pop() ?? c.filePath;
            const blocking = c.blocking ? " · **blocking**" : "";
            lines.push(`- \`${fileName}:${c.line}\`${blocking} — ${c.body}`);
            if (c.suggestion) {
                const fix = c.suggestion.trim().replace(/\n/g, " ").slice(0, 150);
                lines.push(`  - **Fix:** \`${fix}\``);
            }
        }
        lines.push("");
    }

    lines.push("---");
    lines.push(`*Reviewed ${state.changedFiles.length} file${state.changedFiles.length !== 1 ? "s" : ""} in ${durationSec}s · Generated by [PullRabbit](https://github.com/apps/pull-rabbit)*`);

    return lines.join("\n");
};

export const postReview = async (state: PRReviewStateType): Promise<Partial<PRReviewStateType>> => {
    const startedAt = Date.now();
    const octokit = createInstallationOctokit(state.githubInstallationId);

    const session = await db.reviewSession.findUnique({
        where: { id: state.reviewSessionId },
        select: { githubLoadingCommentId: true, createdAt: true },
    });
    const loadingCommentId = session?.githubLoadingCommentId ?? null;
    const queuedAt = session?.createdAt ? session.createdAt.getTime() : startedAt;
    const totalDurationMs = Date.now() - queuedAt;

    try {
        await db.reviewSession.update({
            where: { id: state.reviewSessionId },
            data: { status: "RUNNING" },
        });

        if (state.error) {
            await db.reviewSession.update({
                where: { id: state.reviewSessionId },
                data: { status: "FAILED", errorMessage: state.error, completedAt: new Date() },
            });
            if (loadingCommentId) {
                try {
                    await octokit.rest.issues.updateComment({
                        owner: state.owner,
                        repo: state.repoName,
                        comment_id: Number(loadingCommentId),
                        body: "**PullRabbit** encountered an error during review. Please try again.",
                    });
                } catch { /* best-effort */ }
            }
            return {};
        }

        const comments = state.allComments;
        const body = buildComment(state, comments, totalDurationMs);

        try {
            if (loadingCommentId) {
                await octokit.rest.issues.updateComment({
                    owner: state.owner,
                    repo: state.repoName,
                    comment_id: Number(loadingCommentId),
                    body,
                });
            } else {
                await octokit.rest.issues.createComment({
                    owner: state.owner,
                    repo: state.repoName,
                    issue_number: state.prNumber,
                    body,
                });
            }
        } catch { /* best-effort */ }

        if (comments.length > 0) {
            await db.reviewComment.createMany({
                data: comments.map((c) => ({
                    reviewSessionId: state.reviewSessionId,
                    filePath: c.filePath,
                    line: c.line,
                    startLine: c.startLine ?? null,
                    body: c.body,
                    severity: c.severity,
                    category: c.category,
                    suggestion: c.suggestion ?? null,
                })),
            });
        }

        await db.reviewSession.update({
            where: { id: state.reviewSessionId },
            data: {
                status: "COMPLETED",
                filesReviewed: state.changedFiles.length,
                totalComments: comments.length,
                completedAt: new Date(),
            },
        });

        return {};
    } catch (err) {
        console.error("postReview failed:", err);
        await db.reviewSession.update({
            where: { id: state.reviewSessionId },
            data: { status: "FAILED", errorMessage: String(err), completedAt: new Date() },
        });
        return { error: String(err) };
    } finally {
        if (state.repoLocalPath) {
            await cleanupRepo(state.repoLocalPath);
        }
    }
};
